server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_service
    username: root
    password: 6209

  jpa:
    show-sql: true
    hibernate. ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


